// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlxntdwimegzjqvmkepj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhseG50ZHdpbWVnempxdm1rZXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTc4ODEsImV4cCI6MjA3MjkzMzg4MX0.jz07ynYc_lSceIc3cpHyefVs7Z5BIZl8uC_4OijWJTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});